name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: vercel-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Deploy to Vercel (production)
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: team_Y6cENa9uVKU1nqzMDA0zBKsE
          vercel-project-id: prj_o24WfCY6uXi9sAWXrHikH2YWB9N1
          working-directory: ./
          vercel-args: '--prod --yes'